name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: testing
      run: |
        sudo apt install -y virtualbox
        VBoxManage list vms
        wget https://homepages.cwi.nl/~hannes/86Cv27lf5353lJR/Solaris10_1-13_VM.ova
        VBoxManage import Solaris10_1-13_VM.ova
        VBoxManage modifyvm --natpf1 ssh,tcp,0.0.0.0,2222,0.0.0.0,22
        VBoxManage startvm "Solaris10_1-13" --type headless
        for (( ; ; )); do ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@localhost:2222 ls; sleep 1; done
        
